on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: qikaacr.azurecr.io
        username: ${{ secrets.acr_qikaacr_username }}
        password: ${{ secrets.acr_qikaacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Composer" -f  "Composer/Dockerfile" -t qikaacr.azurecr.io/qikak8s:${{ github.sha }}
        docker push qikaacr.azurecr.io/qikak8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_qikak8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep qikak8sd904 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace qikak8sd904`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: qikak8sd904
        container-registry-url: qikaacr.azurecr.io
        container-registry-username: ${{ secrets.acr_qikaacr_username }}
        container-registry-password: ${{ secrets.acr_qikaacr_password }}
        secret-name: qikak8sdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: qikak8sd904
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          qikaacr.azurecr.io/qikak8s:${{ github.sha }}
        imagepullsecrets: |
          qikak8sdockerauth